#!/bin/sh -x
java -jar ClientRunner-jar-with-dependencies.jar -u https://uicds-test3.saic.com/uicds/ws -f ../../../data/inc2Demo/Richmond/CCA.xml
java -jar ClientRunner-jar-with-dependencies.jar -u https://uicds-test3.saic.com/uicds/ws -f ../../../data/inc2Demo/Richmond/Agreement/agreement-Richmond.xml 

java -jar ClientRunner-jar-with-dependencies.jar -u https://uicds-test3.saic.com/uicds/ws -f ../../../data/inc2Demo/Test/Bert-Test3.xml
java -jar ClientRunner-jar-with-dependencies.jar -u https://uicds-test3.saic.com/uicds/ws -f ../../../data/inc2Demo/Test/John-Test3.xml
java -jar ClientRunner-jar-with-dependencies.jar -u https://uicds-test3.saic.com/uicds/ws -f ../../../data/inc2Demo/Test/Daniel-Test3.xml
java -jar ClientRunner-jar-with-dependencies.jar -u https://uicds-test3.saic.com/uicds/ws -f ../../../data/inc2Demo/Test/Roger-Test3.xml
java -jar ClientRunner-jar-with-dependencies.jar -u https://uicds-test3.saic.com/uicds/ws -f ../../../data/inc2Demo/Test/Paul-Test3.xml
java -jar ClientRunner-jar-with-dependencies.jar -u https://uicds-test3.saic.com/uicds/ws -f ../../../data/inc2Demo/Test/Jay-Test3.xml
java -jar ClientRunner-jar-with-dependencies.jar -u https://uicds-test3.saic.com/uicds/ws -f ../../../data/inc2Demo/Richmond/Traffic/IRRIS-Profile.xml

