package com.saic.uicds.core.em.util;

import java.io.ByteArrayInputStream;
import java.io.File;

import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;

import org.junit.Test;
import org.uicds.alertService.CreateAlertRequestDocument;

public class XmlEncodingTest {

    @Test
    public void testEncoding() {

        DocumentBuilder builder = null;
        // original xml String representation
        String alertXml = null;
        // the String generated by getBytes
        String alertOne = null;
        // the String generated by getBytes with charset of UTF-8
        String alertTwo = null;
        byte[] bytes = null;
        try {
            CreateAlertRequestDocument createAlert = CreateAlertRequestDocument.Factory.parse(new File(
                "src/test/resources/alerts/CreateAlertOtherEncoding.xml"));
            alertXml = createAlert.getCreateAlertRequest().getAlert().xmlText();
            builder = DocumentBuilderFactory.newInstance().newDocumentBuilder();
            // the getBytes will return bytes which is not UTF-8 encoding
            bytes = alertXml.getBytes();
            alertOne = new String(bytes);
            builder.parse(new ByteArrayInputStream(bytes));
        } catch (Exception e) {
            System.err.println("Parsing with default charset: " + e.getMessage());
            try {
                // request to return the bytes in UTF-8 charset
                bytes = alertXml.getBytes("UTF-8");
                alertTwo = new String(bytes, "UTF-8");
                builder.parse(new ByteArrayInputStream(bytes));
                System.err.println("Parsing with UTF-8 successful");
            } catch (Exception ee) {
                System.err.println("Parsing with UTF-8: " + ee.getMessage());
            }
        }
        System.err.println("alertXml and alertOne are "
            + (alertXml.equals(alertOne) ? "same" : "not the same"));
        System.err.println("alertXml and alertTwo are "
            + (alertXml.equals(alertTwo) ? "same" : "not the same"));
        System.err.println("alertOne and alertTwo are "
            + (alertOne.equals(alertTwo) ? "same" : "not the same"));
        // System.err.println("alertOne\n" + alertOne);
        // System.err.println("alertTwo\n" + alertTwo);
    }
}
